POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA2NzI0MDE3LCJ1c2VySWQiOjF9.GAw0X71jbG3umupdsZitJsBK6Io7wucEmY9Co2jQWOA

{
    "name": "Test event",
    "description": "A test event",
    "location": "Test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}