POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA2NzgyMDk2LCJ1c2VySWQiOjJ9.Q_sD6GNYW5YvhGe882OCBBSa4TyRwNyw3V1rMZWG0MI

{
    "name": "Test event",
    "description": "A test event",
    "location": "Test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}