DELETE http://localhost:8080/events/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA2NzgyMzU2LCJ1c2VySWQiOjF9.ZjGeyCjFCs_YLzyAK7bVDcL7esVd5QaBQFufGlNQ-2w