PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzA2NzI0NzU2LCJ1c2VySWQiOjF9.CgdYv9k_dIm5P9gmm7f5ocaR7-MO_VD491cCw48l7bY

{
    "name": "Updated Event Title",
    "description": "Updated test event",
    "location": "Updated Test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}