PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Updated Event Title",
    "description": "Updated test event",
    "location": "Updated Test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}